
// =====================================================================
//  Rendering
// =====================================================================
// "海音" (Umine) as a 32x16 1-bit bitmap (generated by tools/gen_kanji.js
// from a local CJK font, embedded so it renders identically offline).
const KANON_KANJI = ["00000000000000000000000000000000","00100001000000000000000110000000","00110011000000000000000110000000","00001011111111100011111111111100","00000110000000000000110000010000","00000110000000000000110000110000","01100111111111000000010000100000","00110011001001000111111111111110","00010011001001000000000000000000","00000011011001000001111111111000","00001111111111110001100000001000","00010010011001000001100000001000","00110010010001000001111111111000","00110111111111110001100000001000","00100110000011000001100000001000","01100000000011000001111111111000"];
const kanjiCv = mkCanvas(34, 17);
(function buildKanji() {
  const kg = kanjiCv.getContext('2d');
  for (let pass = 0; pass < 2; pass++) {
    kg.fillStyle = pass ? '#ffffff' : '#120e24';
    for (let y = 0; y < 16; y++) for (let x = 0; x < 32; x++) if (KANON_KANJI[y].charCodeAt(x) === 49) kg.fillRect(x + (pass ? 0 : 1), y + (pass ? 0 : 1), 1, 1);
  }
})();

function drawLilyLandmarks(camX) {
  const F = (x, y, w, h, col) => { g.fillStyle = col; g.fillRect(x, y, w, h); };
  const screenX = wx => wx - camX;

  // Screen 0: theatre gate silhouette, curtains and marquee bulbs.
  let x = Math.round(screenX(118));
  if (x > -90 && x < VW + 90) {
    F(x - 42, 86, 84, 77, '#2c183d');
    F(x - 37, 91, 74, 72, '#4d2a59');
    F(x - 31, 96, 62, 67, '#24132f');
    for (let k = -3; k <= 3; k++) {
      const bx = x + k * 10;
      F(bx - 1, 89, 3, 3, (frame >> 4) & 1 ? '#fff0bb' : '#ffd0ea');
    }
    F(x - 30, 98, 6, 48, '#7a355f'); F(x + 24, 98, 6, 48, '#7a355f');
    for (let yy = 101; yy < 145; yy += 8) {
      F(x - 29, yy, 5, 2, '#b94f7d'); F(x + 24, yy + 3, 5, 2, '#b94f7d');
    }
  }

  // Screen 1: backstage rigging, hanging lamps and ropes.
  x = Math.round(screenX(16 * 16 + 128));
  if (x > -110 && x < VW + 110) {
    F(x - 90, 55, 180, 3, '#39284d');
    for (let k = -4; k <= 4; k++) {
      const lx = x + k * 20;
      F(lx, 58, 1, 20 + (Math.abs(k) % 3) * 5, '#5b456f');
      const ly = 78 + (Math.abs(k) % 3) * 5;
      F(lx - 4, ly, 9, 3, '#6a486b');
      F(lx - 2, ly + 3, 5, 4, (frame >> 5) & 1 ? '#ffe9b0' : '#ffd0ea');
    }
    F(x - 74, 116, 42, 2, '#72506f');
    F(x + 35, 104, 38, 2, '#72506f');
  }

  // Screen 2: stage-machinery towers with moving decorative bulbs.
  x = Math.round(screenX(32 * 16 + 128));
  if (x > -120 && x < VW + 120) {
    for (const ox of [-72, 58]) {
      F(x + ox, 78, 8, 84, '#342141');
      for (let yy = 82; yy < 158; yy += 12) {
        F(x + ox + 2, yy, 4, 2, '#6f4c76');
        if (((yy + frame) >> 4) & 1) F(x + ox + 3, yy - 3, 2, 2, '#ffd7ef');
      }
    }
    F(x - 70, 88, 132, 3, '#463054');
    F(x - 48, 121, 96, 2, '#5f3d68');
    for (let k = -5; k <= 5; k++) {
      const sx = x + k * 11;
      const sy = 72 + ((k & 1) ? 4 : 0);
      F(sx, sy, 1, 10, '#5d466d');
      F(sx - 1, sy + 10, 3, 3, ((frame >> 4) + k) & 1 ? '#fff1bc' : '#eaa5d5');
    }
  }

  // Screen 3: dressing-room wing / side-stage corridor. Mirrors and vanity bulbs
  // make this feel like the last quiet space before the show.
  x = Math.round(screenX(48 * 16 + 128));
  if (x > -120 && x < VW + 120) {
    F(x - 84, 92, 56, 54, '#311d3f');
    F(x - 78, 98, 44, 36, '#5a365f');
    F(x - 74, 102, 36, 28, '#2a1833');
    for (let k = 0; k < 7; k++) {
      const bx = x - 82 + k * 9;
      F(bx, 94, 2, 2, ((frame >> 4) + k) & 1 ? '#fff0bb' : '#ffd0ea');
      F(bx, 136, 2, 2, ((frame >> 5) + k) & 1 ? '#fff0bb' : '#e7a6cf');
    }
    for (let k = 0; k < 5; k++) {
      const by = 101 + k * 8;
      F(x - 84, by, 2, 2, ((frame >> 4) + k) & 1 ? '#fff0bb' : '#ffd0ea');
      F(x - 30, by, 2, 2, ((frame >> 4) + k + 1) & 1 ? '#fff0bb' : '#ffd0ea');
    }
    F(x + 34, 84, 10, 74, '#2f1b3c');
    F(x + 46, 84, 10, 74, '#40244d');
    F(x + 58, 84, 10, 74, '#2f1b3c');
    F(x + 32, 82, 38, 3, '#6b3f68');
    F(x + 31, 158, 40, 3, '#6b3f68');
  }

  // Screen 4: quiet side-stage corridor. Sparse lights leave breathing room before the boss.
  x = Math.round(screenX(64 * 16 + 128));
  if (x > -130 && x < VW + 130) {
    F(x - 96, 76, 192, 3, '#35233f');
    for (let k = -4; k <= 4; k++) {
      const lx = x + k * 22;
      F(lx, 79, 1, 28, '#51365d');
      if (k % 2 === 0) F(lx - 2, 106, 5, 3, '#8b5a82');
    }
    F(x - 70, 146, 140, 2, '#654563');
    F(x + 46, 118, 8, 24, '#47314d');
    F(x + 48, 114, 4, 4, ((frame >> 5) & 1) ? '#fff1b8' : '#d59bc4');
  }

  // Screen 5 / boss room: the corridor opens into a proper stage proscenium.
  x = Math.round(screenX(80 * 16 + 128));
  if (x > -150 && x < VW + 150) {
    F(x - 112, 48, 224, 6, '#2b1838');
    F(x - 106, 54, 212, 3, '#7a456e');
    for (let k = -8; k <= 8; k++) {
      const lx = x + k * 12;
      F(lx, 55, 1, 18 + (Math.abs(k) % 2) * 4, '#5b3a63');
      const lit = (((frame >> 3) + k) & 3) !== 0;
      F(lx - 2, 73 + (Math.abs(k) % 2) * 4, 5, 5, lit ? '#fff2ba' : '#b86893');
    }
    F(x - 104, 83, 14, 79, '#6f3058');
    F(x + 90, 83, 14, 79, '#6f3058');
    for (let yy = 88; yy < 158; yy += 10) {
      F(x - 102, yy, 10, 3, '#b84e7e');
      F(x + 92, yy + 4, 10, 3, '#b84e7e');
    }
    // Decorative footlights point toward Lily's arena.
    for (let k = -5; k <= 5; k++) {
      const fx = x + k * 16;
      F(fx - 2, 158, 5, 3, '#4d304f');
      if (((frame >> 4) + k) & 1) F(fx - 1, 154, 3, 4, '#ffd9ef');
    }
  }

  // Ambient floating glitter only in Lily's stage; decorative, no collision.
  for (let i = 0; i < 18; i++) {
    const h = hash(i, 911);
    const wx = (h % (48 * 16)) + ((frame * (0.05 + (i % 3) * 0.015)) % (48 * 16));
    const sx = Math.floor(screenX(wx % (48 * 16)));
    if (sx < 0 || sx >= VW) continue;
    const y = 48 + ((h >>> 8) % 118) + Math.round(Math.sin(frame * 0.025 + i) * 2);
    F(sx, y, 1, 1, i % 3 === 0 ? '#fff1b8' : '#ffd2ef');
  }
}

function drawBackground(camX) {
  g.drawImage(skyCv, 0, 0);
  let fx = -Math.floor(camX * 0.15) % 512; if (fx > 0) fx -= 512;
  g.drawImage(farCv, fx, 0); g.drawImage(farCv, fx + 512, 0);
  if (curArea.id === 'lily') drawLilyLandmarks(camX);
  if (curArea.final && state !== 'title') drawFinalBackdrop(camX);
  let nx = -Math.floor(camX * 0.4) % 512; if (nx > 0) nx -= 512;
  g.drawImage(nearCv, nx, 0); g.drawImage(nearCv, nx + 512, 0);
}

// ---- character draw functions (swap these for sprite-sheet images later) ----
// drawPlayer: picks a pose frame from SPR.hero and anchors it so the sprite's
// feet sit on the hitbox bottom and its body centre on the hitbox centre.
function heroPose(p) {
  if (p.hurt > 0) return 'hurt';
  if (!p.onGround) return 'jump';
  if (p.vx !== 0) { const f = (p.animT >> 3) & 3; return f === 0 ? 'run0' : f === 2 ? 'run2' : 'run1'; }
  return 'stand';
}
function drawPlayer(camX) {
  const p = P; if (p.dead) return;
  if (curArea.final && state === 'climax' && FINAL.climaxT >= CLIMAX_UMINE && FINAL.climaxT < CLIMAX_UMINE + 300) return; // drawn by drawUmineAwaken
  if (p.inv > 0 && p.inv < 9000 && p.hurt <= 0 && ((p.inv >> 2) & 1)) return; // mercy blink
  const shoot = p.shootT > 0 && p.hurt <= 0 ? 1 : 0;
  const white = p.hurt > 0 && (p.hurt & 2);
  if (SEQUEL_MODEL.size !== 32 && SEQUEL_MODEL.frames.length) { drawSequelPlayer(camX, white); return; }
  if (SHEETS.kanon) { // real sprite sheet (32x32, feet at the bottom row)
    let anim, i = 0;
    if (p.hurt > 0) anim = 'hurt';
    else if (!p.onGround) anim = p.vy < 0 ? 'jump' : 'fall';
    else if (p.vx !== 0) { anim = shoot ? 'runshoot' : 'run'; i = p.animT >> 3; }
    else { anim = shoot ? 'shoot' : 'idle'; i = frame >> 5; }
    const K = SHEET_DEFS.kanon, cx = p.face >= 0 ? K.cx : K.fw - K.cx;
    g.drawImage(pick(sheetFrame('kanon', anim, i), p.face, white), Math.round(p.x + p.w / 2 - cx - camX), Math.round(p.y + p.h - K.fh));
    return;
  }
  const img = pick(SPR.hero[heroPose(p)][shoot], p.face, white);
  const cx = p.face >= 0 ? HERO_CX : HERO_W - HERO_CX;
  g.drawImage(img, Math.round(p.x + p.w / 2 - cx - camX), Math.round(p.y + p.h - HERO_H));
}
function drawWalker(e, camX, white) { g.drawImage(pick(SPR.walker[(e.t >> 3) & 1], e.face, white), Math.round(e.x - e.ox - camX), Math.round(e.y - e.oy)); }
function drawHopper(e, camX, white) { g.drawImage(pick(SPR.hopper[e.onGround ? 0 : 1], e.face, white), Math.round(e.x - e.ox - camX), Math.round(e.y - e.oy)); }
function drawFlyer(e, camX, white) { if (curArea.final) { drawFinalGhostEnemy(e, camX, white); return; } g.drawImage(pick(SPR.flyer[(e.t >> 2) & 1], e.face, white), Math.round(e.x - e.ox - camX), Math.round(e.y - e.oy)); }
function drawEnemy(e, camX) {
  const white = e.flash > 0 && (e.flash & 2);
  if (e.type === 'W') drawWalker(e, camX, white); else if (e.type === 'H') drawHopper(e, camX, white); else drawFlyer(e, camX, white);
}
// Tobiume: dark = tobiume_dark.png (48x48) / rescued = tobiume.png (normal, 32x32, 15 frames)
// or procedural 40x40 art. Anchored on the hitbox bottom-centre (feet) with the per-sheet body centre.
function drawTobiume(camX) {
  const b = boss;
  let white = (b.flash > 0 && (b.flash & 2)) || ((b.state === 'swoopWind' || b.state === 'kickWind') && (b.t & 4));
  if (b.state === 'rescue' && b.t < 70) white = (b.t & 4) !== 0;
  const mx = Math.round(b.x + b.w / 2 - camX), by = Math.round(b.y + b.h + b.hopY); // hitbox bottom-centre
  const wingF = (b.state === 'swoop' || b.state === 'kick') ? 1 : (frame >> 3) & 1;
  const normal = !b.dark && SHEETS.tobiumeNormal;
  const sh = b.dark ? SHEETS.tobiume : (SHEETS.tobiumeNormal || SHEETS.tobiumeTint);
  if (sh) {
    const T = normal ? SHEET_DEFS.tobiumeNormal : SHEET_DEFS.tobiume;
    let fi;
    if (b.pose === 'kick' && normal && T.map.kick) fi = T.map.kick[0] + Math.min(b.poseF, T.map.kick[1] - 1); // 7 wind-up / 8 hop / 9 front kick / 10 hit flash
    else {
      const anim = b.pose === 'idle' ? 'idle' : b.pose === 'fly' ? 'fly' : (b.pose === 'attack' || b.pose === 'kick') ? 'attack' : b.pose === 'hurt' ? 'hurt' : (T.map.defeat ? 'defeat' : 'hurt');
      const m = T.map[anim] || T.map.idle;
      fi = anim === 'attack' ? m[0] + (b.fireT > 0 ? 1 : 0) : m[0] + (((anim === 'idle' && normal) ? (frame >> 4) : wingF) % m[1]); // dark frame 5 = firing moment
    }
    g.drawImage(pick(sh[fi], b.face, white), mx - (b.face >= 0 ? T.cx : T.fw - T.cx), by - T.fh);
  } else {
    const pose = b.pose === 'kick' && !b.dark && b.state === 'rescue' ? (b.poseF === 0 ? 'attack' : 'kick') : b.pose;
    g.drawImage(pick(SPR.tobi[b.dark ? 'dark' : 'normal'][pose][wingF], b.face, white), mx - 20, by - 39);
  }
}
function drawLilyBossSpotlight(camX) {
  if (curArea.boss !== 'lily' || !boss.triggered || boss.state === 'off') return;
  const cx = Math.round(boss.x + boss.w / 2 - camX);
  const rainShow = boss.state === 'lilyRain';
  g.save();
  g.globalAlpha = (rainShow ? 0.22 : 0.10) + (rainShow ? 0.07 : 0.03) * Math.sin(frame * (rainShow ? 0.11 : 0.05));
  g.fillStyle = rainShow ? '#fff4c9' : '#ffe9fa';
  g.beginPath();
  g.moveTo(cx - (rainShow ? 8 : 5), 30);
  g.lineTo(cx - (rainShow ? 50 : 42), FLOOR_Y);
  g.lineTo(cx + (rainShow ? 50 : 42), FLOOR_Y);
  g.lineTo(cx + (rainShow ? 8 : 5), 30);
  g.closePath(); g.fill();
  if (rainShow) {
    g.globalAlpha = 0.24 + 0.08 * Math.sin(frame * 0.15);
    g.fillStyle = '#ffffff';
    g.fillRect(cx - 1, 30, 2, FLOOR_Y - 30);
  }
  g.restore();
}

function drawBoss(camX) {
  const b = boss; if (b.state === 'off') return;
  if (curArea.boss === 'tobiume') { drawTobiume(camX); return; }
  if (curArea.final && (curArea.boss === 'kanata' || curArea.boss === 'mimic')) { drawFinalBoss(camX); return; }
  drawBossMarks(camX);
  if (b.hidden || b.alpha <= 0) return;
  const T = BOSS_TYPES[curArea.boss];
  let white = b.flash > 0 && (b.flash & 2);
  if ((b.state === 'crouch' && b.t < 10) || (b.state === 'warpOut' && b.t < 6)) white = white || (b.t & 2) !== 0; // telegraph flash
  if (b.state === 'rescue' && b.t < 70) white = (b.t & 4) !== 0;
  if (curArea.boss === 'disaster' && b.state === 'disMorph') white = white || ((b.t >> 1) & 3) === 0; // morph flash
  const mx = Math.round(b.x + b.w / 2 - camX), by = Math.round(b.y + b.h + b.hopY); // hitbox bottom-centre
  const key = b.dark ? T.dark : T.normal, sh = SHEETS[key];
  const shA = curArea.final ? finalShadowAlpha() : 1;
  if (b.alpha < 1 || shA < 1) g.globalAlpha = b.alpha * shA;
  if (sh) {
    const D = SHEET_DEFS[key]; let fi;
    if (b.dark && D.map) {
      const m = D.map[b.pose] || D.map.idle;
      fi = m[0] + (b.poseF >= 0 ? Math.min(b.poseF, m[1] - 1) : ((frame >> (b.pose === 'idle' ? 4 : 3)) % m[1]));
    } else { // normal 32x32 friend sheets: 2 frames (Neenia: 1 = bow shot, so her idle stays on 0)
      fi = b.poseF >= 0 ? b.poseF : (curArea.boss === 'neenia' ? 0 : (frame >> 5) & 1);
      fi = Math.min(fi, sh.length - 1);
    }
    const cx = D.cxF ? D.cxF[fi] : D.cx;
    if (curArea.boss === 'diceroll' && b.dark && b.flash > 0 && (b.flash & 2) && b.state !== 'rescue') { if (D.map && b.flash > 7) fi = D.map.hurt[0]; g.drawImage(dicerollRedFrame(sh, fi, b.face), Math.round(mx - (b.face >= 0 ? cx : D.fw - cx)), by - D.fh); }
    else if (curArea.boss === 'shiranui' && b.dark) { if (D.map && b.flash > 7 && b.state !== 'shIllusion') fi = D.map.hurt[0]; drawShiranuiBody(b, sh, D, fi, mx, by, camX); }
    else g.drawImage(pick(sh[fi], b.face, white), mx - (b.face >= 0 ? cx : D.fw - cx), by - D.fh);
    if (curArea.boss === 'lily' && b.dark && lilySongFxActive(b) && SHEETS.lilySongWave) {
      const W = SHEET_DEFS.lilySongWave, fx = SHEETS.lilySongWave[0];
      g.drawImage(pick(fx, b.face, false), mx - (b.face >= 0 ? W.cx : W.fw - W.cx), by - W.fh);
    }
  } else { // procedural fallback (?sprites=0): the ally sprite, shadow-tinted while dark
    const k = T.ally || 'A', f = b.pose === 'attack' ? 1 : 0;
    let spr = SPR.ally[k][f];
    if (b.dark) { SPR.allyDark = SPR.allyDark || {}; const ck = k + f; if (!SPR.allyDark[ck]) SPR.allyDark[ck] = sheetSprite(tintCanvas(spr.r, '#1a0828', 0.72)); spr = SPR.allyDark[ck]; }
    g.drawImage(pick(spr, b.face, white), mx - 16, by - 32);
  }
  g.globalAlpha = 1;
  if (curArea.boss === 'disaster' && b.dark) drawDisasterWeaponLayer(b, mx, by);
  if (curArea.boss === 'diceroll' && b.dark) drawDicerollOverlay(b, mx, by, camX);
}
// telegraphs drawn under the boss: aim line, arrow-rain columns, warp mark
function drawBossMarks(camX) {
  const b = boss, blink = (frame >> 2) & 1;
  if (curArea.boss === 'disaster') drawDisasterMarks(b, camX, blink);
  if (curArea.boss === 'shiranui') drawShiranuiMarks(b, camX, blink);
  if (curArea.boss === 'diceroll') drawDicerollMarks(b, camX, blink);
  if (b.aimShow) { // Neenia's aim: dotted line to the predicted spot
    const dx = b.aimX - b.mx, dy = b.aimY - b.my, len = Math.hypot(dx, dy) || 1, n = Math.min(40, Math.floor(len / 6));
    g.fillStyle = blink ? '#ff5a8a' : '#ffb0c8';
    for (let k = 1; k <= n; k++) g.fillRect(Math.round(b.mx + dx / len * k * 6 - camX), Math.round(b.my + dy / len * k * 6), 1, 1);
    const ax = Math.round(b.aimX - camX), ay = Math.round(b.aimY);
    g.fillRect(ax - 3, ay, 2, 1); g.fillRect(ax + 2, ay, 2, 1); g.fillRect(ax, ay - 3, 1, 2); g.fillRect(ax, ay + 2, 1, 2);
  }
  if (curArea.boss === 'lily' && b.state === 'lilyRain' && b.t > 0 && b.t < 30) {
    // Live-show cue: ceiling glitter replaces the old fixed danger columns.
    // The stronger spotlight on Lily is the main telegraph; these sparkles tell
    // the player that the next threat comes from above.
    for (let i = 0; i < 7; i++) {
      const cx = Math.round(ROOM_L + (i + 0.5) * (ROOM_R - ROOM_L) / 7 - camX);
      const yy = 31 + ((i * 5 + frame) % 7);
      g.fillStyle = blink ? '#fff6c0' : '#ffd2ef';
      g.fillRect(cx - 2, yy, 5, 1); g.fillRect(cx, yy - 2, 1, 5);
    }
  }
  if (curArea.boss === 'lily' && b.state === 'lilyLine') {
    const times = lilyLineTimes(bossRage());
    for (let i = 0; i < times.length; i++) {
      const dt = times[i] - b.t;
      if (dt >= 0 && dt <= 12) {
        const high = lilyLineHighAt(b, i);
        const yy = high ? FLOOR_Y - 43 : FLOOR_Y - 14;
        g.fillStyle = high ? 'rgba(255,230,150,0.15)' : 'rgba(255,160,210,0.16)';
        g.fillRect(Math.round(ROOM_L - camX), yy - 4, ROOM_R - ROOM_L, 9);
        g.fillStyle = blink ? '#fff6c0' : '#ffd070';
        for (let x = ROOM_L; x < ROOM_R; x += 8) g.fillRect(Math.round(x - camX), yy, 4, 1);
        break;
      }
    }
  }
  if (b.rainN > 0) { // marked rain columns
    for (let i = 0; i < b.rainN; i++) {
      const x = b.rainC[i] * TS - camX;
      g.fillStyle = b.warn > 0 && b.warn < 20 ? 'rgba(255,60,100,0.24)' : 'rgba(255,60,100,0.13)'; g.fillRect(x + 2, TS, 12, FLOOR_Y - TS);
      g.fillStyle = blink ? '#ff4a7a' : '#ffd0dc';
      g.fillRect(x + 3, 27, 10, 2); g.fillRect(x + 5, 29, 6, 2); g.fillRect(x + 7, 31, 2, 2);                   // ▼ just below the HUD bars
      g.fillRect(x + 2, FLOOR_Y - 2, 12, 2);                                                                  // floor line
    }
  }
  if (b.ricoShow && b.ricoN > 1) { // Neenia's ricochet: dotted bounce path (dim while tracking, bright + dense once locked)
    const lock = b.ricoLock, stepD = lock ? 3 : 6;
    g.fillStyle = lock ? (blink ? '#ffffff' : '#7fe8ff') : (blink ? '#5ab8d8' : '#9ad8f0');
    for (let i = 0; i < b.ricoN - 1; i++) {
      const x0 = b.ricoPts[i * 2], y0 = b.ricoPts[i * 2 + 1], x1 = b.ricoPts[i * 2 + 2], y1 = b.ricoPts[i * 2 + 3];
      const len = Math.hypot(x1 - x0, y1 - y0), n = Math.floor(len / stepD);
      for (let k = 1; k <= n; k++) g.fillRect(Math.round(x0 + (x1 - x0) * k / n - camX), Math.round(y0 + (y1 - y0) * k / n), lock ? 2 : 1, lock ? 2 : 1);
      if (i < b.ricoN - 2) { const bx = Math.round(x1 - camX), by = Math.round(y1); g.fillRect(bx - 2, by, 5, 1); g.fillRect(bx, by - 2, 1, 5); } // bounce point
    }
  }
  for (let i = 0; i < b.markT.length; i++) { // lob / snare landing marks on the floor (shrinking ring = time left)
    if (b.markT[i] <= 0) continue;
    const x = Math.round(b.markX[i] - camX), y = FLOOR_Y, snare = b.markK[i] === 1, f = b.markT[i] / b.markMax[i], fast = b.markT[i] < 16 ? (frame >> 1) & 1 : blink;
    const col = snare ? (fast ? '#5aff8a' : '#e0ffe8') : (fast ? '#ff4a7a' : '#ffd0dc');
    g.fillStyle = snare ? 'rgba(90,255,138,0.14)' : 'rgba(255,60,100,0.14)'; g.fillRect(x - 6, y - 30, 12, 28);
    g.fillStyle = col;
    const r = 4 + Math.round(f * 6);
    for (let k = -r; k <= r; k++) { const hh = Math.round(Math.sqrt(Math.max(0, 1 - (k / r) * (k / r))) * 2.5); g.fillRect(x + k, y - 2 - hh, 1, 1); g.fillRect(x + k, y - 2 + hh, 1, 1); }
    g.fillRect(x - 3, y - 12, 7, 2); g.fillRect(x - 2, y - 10, 5, 1); g.fillRect(x - 1, y - 9, 3, 1); g.fillRect(x, y - 8, 1, 1); // small ▼
    if (snare) { g.fillRect(x - 5, y - 6, 1, 3); g.fillRect(x + 5, y - 6, 1, 3); g.fillRect(x, y - 7, 1, 3); }            // thorn hint
  }
  if (b.starRainT && b.starX) { // persistent gold columns while she moves and uses other attacks
    for (let k = 0; k < 3; k++) {
      const at = CONFIG.bosses.astarte.starWarning + (k === 1 ? 0 : k === 0 ? 1 : 2) * CONFIG.bosses.astarte.starInterval;
      if (b.starRainT > at) continue;
      const x = Math.round(b.starX[k] - camX), y = FLOOR_Y;
      g.fillStyle = 'rgba(255,224,160,0.13)'; g.fillRect(x - 7, TS + 2, 14, y - TS - 3);
      g.fillStyle = blink ? '#fff6c0' : '#ffe080';
      g.fillRect(x - 6, y - 2, 12, 2); g.fillRect(x - 1, y - 10, 2, 8);
      g.fillRect(x - 2, TS + 6, 4, 2);
    }
  }
  if (b.state === 'shadowWarn' || b.state === 'shadowDive') { // locked landing point; distinct from warp-slash mark
    const x = Math.round(b.warnX - camX), y = FLOOR_Y;
    g.fillStyle = 'rgba(160,115,255,0.2)'; g.fillRect(x - 12, y - 78, 24, 76);
    g.fillStyle = blink ? '#ffffff' : '#b0b8ff';
    g.fillRect(x - 12, y - 2, 24, 2); g.fillRect(x - 2, y - 6, 4, 6);
    for (let k = -10; k <= 10; k += 5) g.fillRect(x + k, y - 10 - Math.abs(k) / 2, 2, 3);
  }
  if (b.state === 'warpWarn') { // Astarte's reappear mark
    const x = Math.round(b.warnX - camX), y = FLOOR_Y;
    g.fillStyle = blink ? '#ff3a5a' : '#ffc0d0';
    for (let k = -9; k <= 9; k++) { const hh = Math.round(Math.sqrt(1 - (k / 10) * (k / 10)) * 3); g.fillRect(x + k, y - 2 - hh, 1, 1); g.fillRect(x + k, y - 2 + hh, 1, 1); }
    g.fillStyle = 'rgba(255,60,90,0.18)'; g.fillRect(x - 6, y - 40, 12, 38);
    g.fillStyle = blink ? '#ffffff' : '#ff3a5a'; g.fillRect(x - 1, y - 30, 2, 7); g.fillRect(x - 1, y - 21, 2, 2); // "!"
  }
}
// star lantern (checkpoint when Astarte can't be there)
function drawLantern(a, camX) {
  const x = Math.round(a.x - camX), y = a.y, lit = checkpoint;
  g.fillStyle = '#2a2440'; g.fillRect(x - 1, y - 20, 2, 20); g.fillRect(x - 4, y - 1, 8, 1);
  if (lit) { g.fillStyle = 'rgba(255,224,128,0.22)'; g.fillRect(x - 7, y - 32, 14, 14); }
  g.fillStyle = '#4a4070'; g.fillRect(x - 4, y - 29, 8, 9);
  g.fillStyle = lit ? ((frame >> 3) & 1 ? '#ffe080' : '#fff4c0') : '#8090c0'; g.fillRect(x - 3, y - 28, 6, 7);
  g.fillStyle = '#ffffff'; g.fillRect(x - 1, y - 26, 2, 3); g.fillRect(x - 2, y - 25, 4, 1);
  g.fillStyle = '#2a2440'; g.fillRect(x - 3, y - 31, 6, 2);
}
// ---- allies (each has its own draw fn; sheet frames used if assets/ exist) ----
function drawAllySprite(a, key, sheetKey, f, camX) {
  const sh = SHEETS[sheetKey], spr = sh ? sh[f % sh.length] : SPR.ally[key][f & 1];
  const cx = sh ? (a.face >= 0 ? SHEET_DEFS[sheetKey].cx : ALLY_W - SHEET_DEFS[sheetKey].cx) : 16;
  g.drawImage(pick(spr, a.face, false), Math.round(a.x - cx - camX), Math.round(a.y - 32));
}
function drawAstarte(a, camX) {
  drawAllySprite(a, 'A', 'astarte', SHEETS.astarte ? (a.t >> 5) & 1 : ((a.t % 200) < 8 ? 1 : 0), camX);
  if (a.cp) { // checkpoint indicator: little star above her head
    g.fillStyle = checkpoint ? ((frame >> 3) & 1 ? '#ffe080' : '#ffffff') : '#8090c0';
    const x = Math.round(a.x - camX), y = a.y - 38 + ((frame >> 4) & 1);
    g.fillRect(x - 1, y, 3, 1); g.fillRect(x, y - 1, 1, 3);
  }
}
function drawNeenia(a, camX) { drawAllySprite(a, 'N', 'neenia', a.act > 0 ? 1 : 0, camX); }
function drawShiranuiAlly(a, camX) { drawAllySprite(a, 'K', 'shiranui', a.act > 0 ? 5 : (a.t >> 5) & 1, camX); }
function drawDicerollAlly(a, camX) { drawAllySprite(a, 'R', 'diceroll', a.act > 0 ? 4 : ((a.t % 260) < 70 ? 2 : (a.t >> 5) & 1), camX); }
function drawSeiten(a, camX) { drawAllySprite(a, 'S', 'seiten', a.act > 0 ? (a.t >> 4) & 1 : (SHEETS.seiten ? (a.t >> 5) & 1 : 0), camX); }
function drawLilyAlly(a, camX) {
  const sh = SHEETS.lily, sp = sh ? sh[(a.t >> 5) & 1] : null;
  if (sp) g.drawImage(pick(sp, a.face, false), Math.round(a.x - 16 - camX), Math.round(a.y - 32));
}
function drawAllies(camX) {
  for (let i = 0; i < allies.length; i++) {
    const a = allies[i]; if (a.x - camX < -24 || a.x - camX > VW + 24) continue;
    if (a.type === 'L') drawLantern(a, camX); else if (a.type === 'A') drawAstarte(a, camX); else if (a.type === 'N') drawNeenia(a, camX); else if (a.type === 'I') drawLilyAlly(a, camX); else if (a.type === 'K') drawShiranuiAlly(a, camX); else if (a.type === 'R') drawDicerollAlly(a, camX); else drawSeiten(a, camX);
  }
}
function drawArrows(camX) {
  g.fillStyle = '#eef0ff';
  for (let i = 0; i < arrows.length; i++) {
    const r = arrows[i]; if (!r.active) continue;
    if (r.die) { drawDie(r.x + 2 - camX, r.y + 2, r.die - 1, 0.7, frame * 0.3); g.fillStyle = '#eef0ff'; continue; }
    if (r.fox) { drawFoxfire(r.x + 2 - camX, r.y + 2, r.vx, r.vy, (frame >> 2) & 1, 0.75); g.fillStyle = '#eef0ff'; continue; }
    const sp = Math.hypot(r.vx, r.vy) || 1, ux = r.vx / sp, uy = r.vy / sp, x = r.x + 2 - camX, y = r.y + 2;
    for (let k = 0; k < 6; k++) g.fillRect(Math.round(x - ux * k), Math.round(y - uy * k), 1, 1);
  }
  g.fillStyle = '#8fd0ff';
  for (let i = 0; i < arrows.length; i++) { const r = arrows[i]; if (r.active && !r.fox && !r.die) g.fillRect(Math.round(r.x + 1 - camX), Math.round(r.y + 1), 2, 2); }
}
function drawBullet(b, camX) {
  const x = Math.round(b.x - camX), y = Math.round(b.y);
  if (b.dspr >= 0 && SHEETS.disasterBullets) { drawDisasterBulletSprite(b, camX); return; }
  if (b.kind >= 35 && b.kind <= 39) { drawFinalBullet(b, camX); return; }
  if (b.kind >= 40 && b.kind <= 43) { drawDarkUmineBullet(b, camX); return; }
  if (b.kind >= 29 && b.kind <= 34) { drawDicerollBullet(b, camX); return; }
  if (b.kind === 24 || b.kind === 25 || b.kind === 27 || b.kind === 28 || b.sspr >= 0) { drawShiranuiBullet(b, camX); return; }
  if (b.kind === 0) g.drawImage(SPR.ebullet.r, x, y);
  else if (b.kind === 2) g.drawImage(SPR.heart.r, x - 1, y - 1);
  else if (b.kind === 3) g.drawImage(SPR.star.r, x - 1, y - 1);
  else if (b.kind === 4) { // floor shockwave
    g.fillStyle = (frame & 2) ? '#ff5aa8' : '#b040e0'; g.fillRect(x, y + 4, 8, 7); g.fillRect(x + 2, y, 4, 11);
    g.fillStyle = '#ffd0f0'; g.fillRect(x + 3, y + 3, 2, 8);
  } else if (b.kind === 6) { // dark arrow (along its velocity)
    const sp = Math.hypot(b.vx, b.vy) || 1, ux = b.vx / sp, uy = b.vy / sp, cx = b.x + 2.5 - camX, cy = b.y + 2.5;
    g.fillStyle = '#6a4aa0'; for (let k = 2; k < 10; k++) g.fillRect(Math.round(cx - ux * k), Math.round(cy - uy * k), 1, 1);
    g.fillStyle = '#e0c8ff'; g.fillRect(Math.round(cx - ux * 9) - 1, Math.round(cy - uy * 9) - 1, 2, 2);
    g.fillStyle = (frame & 2) ? '#ff4a8a' : '#ffffff'; g.fillRect(Math.round(cx) - 1, Math.round(cy) - 1, 3, 3);
  } else if (b.kind === 7) { // falling rain arrow
    g.fillStyle = '#e0c8ff'; g.fillRect(x, y, 1, 2); g.fillRect(x + 2, y, 1, 2);
    g.fillStyle = '#8a6ac0'; g.fillRect(x + 1, y, 1, 8);
    g.fillStyle = (frame & 2) ? '#ff4a8a' : '#ffffff'; g.fillRect(x, y + 7, 3, 2); g.fillRect(x + 1, y + 9, 1, 1);
  } else if (b.kind === 8) { // cursed-song floor sound wave: three arcs )))
    const dir = b.vx >= 0 ? 1 : -1;
    for (let a = 0; a < 3; a++) {
      g.fillStyle = a === 1 ? '#ffd0dc' : ((frame >> 1) & 1) ? '#ff3a5a' : '#c01a50';
      for (let dy = 0; dy < 26; dy++) { const u = (dy - 12.5) / 12.5, off = Math.round((1 - u * u) * 3) + a * 3; g.fillRect(dir > 0 ? x + off : x + 9 - off, y + dy, 1, 1); }
    }
  } else if (b.kind === 9) { // crescent slash wave
    const dir = b.vx >= 0 ? 1 : -1;
    for (let dy = 0; dy < 20; dy++) { const u = (dy - 9.5) / 9.5, bow = Math.round(Math.sqrt(Math.max(0, 1 - u * u)) * 7), th = Math.max(1, Math.round((1 - Math.abs(u)) * 4));
      const px = dir > 0 ? x + 2 + bow : x + 9 - bow - th;
      g.fillStyle = (frame & 2) ? '#ff2a4a' : '#d01040'; g.fillRect(px, y + dy, th, 1);
      g.fillStyle = '#ffe0e6'; if (th > 2) g.fillRect(dir > 0 ? px + th - 1 : px, y + dy, 1, 1); }
  } else if (b.kind === 21 || b.kind === 22 || b.kind === 23) { drawDisasterBullet(b, x, y);
  } else if (b.kind === 18) { // descending star, warm gold distinguishes it from orbiting orbs
    g.fillStyle = 'rgba(255,224,160,0.24)'; g.fillRect(x - 2, y - 3, 14, 16);
    g.fillStyle = (frame & 2) ? '#ffe0a0' : '#fff6c0';
    g.fillRect(x + 4, y, 2, 10); g.fillRect(x, y + 4, 10, 2);
    g.fillRect(x + 2, y + 2, 6, 6);
    g.fillStyle = '#ffffff'; g.fillRect(x + 4, y + 4, 2, 2);
  } else if (b.kind === 17) { // diagonal moon cleave: luminous scythe-shaped crescent
    const ux = b.vx >= 0 ? 1 : -1, uy = b.vy >= 0 ? 1 : -1;
    g.fillStyle = 'rgba(160,115,255,0.32)'; g.fillRect(x - 2, y - 2, 16, 16);
    for (let k = 0; k < 12; k++) {
      const bow = Math.round(Math.sin(k / 11 * Math.PI) * 5);
      g.fillStyle = (frame & 2) ? '#e0c8ff' : '#b0b8ff';
      g.fillRect(x + (ux > 0 ? bow : 11 - bow), y + (uy > 0 ? k : 11 - k), 2, 1);
    }
    g.fillStyle = '#ffffff'; g.fillRect(x + 5, y + 5, 2, 2);
  } else if (b.kind === 10) { // star orb
    const tw = (frame >> 2) & 1;
    g.fillStyle = 'rgba(255,230,140,0.4)'; g.fillRect(x + 2, y - 2, 4, 12); g.fillRect(x - 2, y + 2, 12, 4); g.fillRect(x, y, 8, 8);
    g.fillStyle = tw ? '#ffe070' : '#fff6c0'; g.fillRect(x + 3, y, 2, 8); g.fillRect(x, y + 3, 8, 2); g.fillRect(x + 2, y + 2, 4, 4);
    g.fillStyle = '#ffffff'; g.fillRect(x + 3, y + 3, 2, 2);
  } else if (b.kind === 11) { // cursed note
    g.fillStyle = (frame & 4) ? '#ff5a7a' : '#ff9ab0'; g.fillRect(x, y + 3, 3, 3); g.fillRect(x + 2, y - 2, 1, 5); g.fillRect(x + 3, y - 2, 2, 1); g.fillRect(x + 4, y - 1, 1, 1);
  } else if (b.kind === 19) { // Lily rhythm note: straight, readable lane projectile
    g.fillStyle = 'rgba(255,210,239,0.22)'; g.fillRect(x - 2, y - 2, 9, 9);
    g.fillStyle = (frame & 4) ? '#ffd2ef' : '#fff1b8';
    g.fillRect(x, y + 3, 3, 3); g.fillRect(x + 2, y - 2, 1, 5); g.fillRect(x + 3, y - 2, 2, 1); g.fillRect(x + 4, y - 1, 1, 1);
    g.fillStyle = '#ffffff'; g.fillRect(x + 1, y + 4, 1, 1);
  } else if (b.kind === 20) { // Lily Starlight Rain: glowing confetti strip
    const flip = ((b.t >> 2) + Math.floor(b.swayPhase || 0)) & 1;
    g.fillStyle = 'rgba(255,220,244,0.22)'; g.fillRect(x - 2, y - 2, 9, 12);
    g.fillStyle = flip ? '#ffd2ef' : '#fff1b8';
    if (flip) { g.fillRect(x, y + 1, 5, 3); g.fillRect(x + 1, y + 4, 3, 3); }
    else { g.fillRect(x + 1, y, 3, 6); g.fillRect(x, y + 2, 5, 2); }
    g.fillStyle = '#ffffff'; g.fillRect(x + 2, y + 2, 1, 1);
  } else if (b.kind === 12) { // scythe slash area (fading arc)
    const dir = b.ang >= 0 ? 1 : -1; g.globalAlpha = Math.max(0, b.life / 12) * 0.7; g.fillStyle = '#ff3a5a';
    for (let dy = 0; dy < b.h; dy += 1) { const u = (dy - b.h / 2) / (b.h / 2), off = Math.round(Math.sqrt(Math.max(0, 1 - u * u)) * (b.w - 6)); g.fillRect(dir > 0 ? x + off : x + b.w - off - 3, y + dy, 3, 1); }
    g.globalAlpha = 1;
  } else if (b.kind === 13 || b.kind === 14 || b.kind === 15) { // v5 Neenia: lobbed (violet) / ricochet (cyan) / snare (green) arrow
    const sp = Math.hypot(b.vx, b.vy) || 1, ux = b.vx / sp, uy = b.vy / sp, cx = b.x + b.w / 2 - camX, cy = b.y + b.h / 2;
    const C = b.kind === 13 ? ['#6a4aa0', '#e0c8ff', '#ff4a8a'] : b.kind === 14 ? ['#2a8ab0', '#c0f4ff', '#7fe8ff'] : ['#2a7a4a', '#c8ffd8', '#5aff8a'];
    g.fillStyle = C[0]; for (let k = 2; k < 10; k++) g.fillRect(Math.round(cx - ux * k), Math.round(cy - uy * k), 1, 1);
    g.fillStyle = C[1]; g.fillRect(Math.round(cx - ux * 9) - 1, Math.round(cy - uy * 9) - 1, 2, 2);
    g.fillStyle = (frame & 2) ? C[2] : '#ffffff'; g.fillRect(Math.round(cx) - 1, Math.round(cy) - 1, 3, 3);
    if (b.kind === 14) { g.fillStyle = 'rgba(127,232,255,0.35)'; g.fillRect(Math.round(cx) - 3, Math.round(cy) - 3, 7, 7); }
  } else if (b.kind === 16) { // thorn patch planted by the snare arrow (blinks before it withers)
    if (b.life > 30 || (frame & 4)) {
      const grow = Math.min(1, b.t / 6);
      g.fillStyle = 'rgba(90,255,138,0.16)'; g.fillRect(x - 1, y - 3, b.w + 2, b.h + 3);
      for (let k = 0; k < b.w; k += 4) { const hh = Math.round((k % 8 ? 6 : 9) * grow);
        g.fillStyle = '#1f5a36'; g.fillRect(x + k, y + b.h - hh, 3, hh);
        g.fillStyle = (frame >> 3) & 1 ? '#5aff8a' : '#9affb8'; g.fillRect(x + k + 1, y + b.h - hh, 1, 2);
        g.fillStyle = '#b070ff'; g.fillRect(x + k + (k % 8 ? 2 : 0), y + b.h - Math.round(hh / 2), 1, 1); }
      g.fillStyle = '#123a22'; g.fillRect(x, y + b.h - 2, b.w, 2);
    }
  } else g.drawImage(SPR.star.r, x - 1, y - 1);
}
function drawShot(s, camX) { g.drawImage(pick(SPR.shot, s.vx, false), Math.round(s.x - camX), Math.round(s.y)); }

function drawDoor(camX) {
  const x = ROOM_X - camX; if (x < -16 || x > VW) return;
  const top = DOOR_ROWS[0] * TS, hgt = DOOR_ROWS.length * TS;
  g.fillStyle = '#2c3148'; g.fillRect(x, top - 3, 16, 3); g.fillRect(x, top + hgt, 16, 1);
  const h = Math.round(hgt * (doorClosed ? 1 : doorAnim));
  if (h <= 0) { g.fillStyle = (frame >> 4) & 1 ? '#ffd84a' : '#b08a20'; g.fillRect(x + 2, top - 2, 12, 1); return; }
  g.fillStyle = '#8a93ab'; g.fillRect(x + 1, top, 14, h);
  g.fillStyle = '#4c536b';
  for (let y = top + 3; y < top + h; y += 4) g.fillRect(x + 1, y, 14, 1);
  g.fillStyle = '#c8d0e6'; g.fillRect(x + 1, top, 1, h);
}
function drawParticles(camX) {
  for (let i = 0; i < parts.length; i++) {
    const p = parts[i]; if (!p.active) continue;
    const x = Math.round(p.x - camX), y = Math.round(p.y);
    if (p.kind === 0) { g.fillStyle = p.col; g.fillRect(x - 1, y - 1, 2, 2); }
    else if (p.kind === 1) {
      const r = (p.max - p.life) * 1.6 + 2; g.fillStyle = p.col;
      for (let k = 0; k < 8; k++) g.fillRect(Math.round(x + DIR8X[k] * r) - 1, Math.round(y + DIR8Y[k] * r) - 1, 2, 2);
    } else if (p.kind === 2) {
      const s = ((p.life >> 2) & 1) ? 4 : 6; g.fillStyle = (p.life >> 3) & 1 ? '#ffffff' : p.col; g.fillRect(x - (s >> 1), y - (s >> 1), s, s);
    } else if (p.kind === 4) { g.fillStyle = p.col; g.fillRect(x, y, 2, 2);
    } else if (p.kind === 5) { // music note
      g.fillStyle = p.col; g.fillRect(x, y + 3, 2, 2); g.fillRect(x + 1, y, 1, 4); g.fillRect(x + 2, y, 1, 1);
    } else if (p.kind === 3) {
      const s = (2 + p.life * 1.5) | 0; g.fillStyle = p.col; g.fillRect(x - (s >> 1), y - (s >> 1), s, s);
    }
  }
}
// HP bar: one pip per HP. Pip pitch shrinks (4 -> 3 -> 2 px) for big HP pools so the bar never grows past
// BAR_MAX_W and the two bars (UMINE left, boss right) never overlap on the 256px screen.
const BAR_MAX_W = 124;
function barGeom(max) { const step = Math.max(2, Math.min(4, Math.floor((BAR_MAX_W - 3) / max))); return { step, pip: step - 1, w: max * step + 3 }; }
function drawBar(x, y, label, val, max, fill, align) {
  const G0 = barGeom(max), st = G0.step, pw = G0.pip, w = G0.w, bx = align === 'r' ? x - w : x;
  g.fillStyle = 'rgba(10,8,24,0.72)'; g.fillRect(bx - 2, y - 2, w + 4, 18);
  if (align === 'r') drawText(label, bx + w, y, 'r', 1, 'r'); else drawText(label, bx + 1, y, 'c', 1);
  for (let i = 0; i < max; i++) { g.fillStyle = i < val ? fill : '#2a2a40'; g.fillRect(bx + 2 + i * st, y + 8, pw, 6); }
  g.fillStyle = '#ffffff';
  for (let i = 0; i < max && i < val; i++) g.fillRect(bx + 2 + i * st, y + 8, pw, 1);
}
function drawWaterOrb(camX) {
  const o = magic.orb; if (!o) return;
  const x = Math.round(o.x - camX), y = Math.round(o.y + Math.sin(frame * 0.11) * 1.5);
  g.fillStyle = 'rgba(91,204,250,0.19)'; g.fillRect(x - 3, y - 5, 30, 17);
  g.fillStyle = '#256889'; g.fillRect(x, y, 24, 7);
  g.fillStyle = '#68d4ff'; g.fillRect(x + 1, y, 22, 3);
  g.fillStyle = '#ddfcff'; g.fillRect(x + 4, y + 1, 8, 1); g.fillRect(x + 17, y + 2, 3, 1);
  g.fillStyle = '#b8edff'; g.fillRect(x + 2, y + 7, 20, 1);
  if (o.life < 70 && (frame & 4)) { g.fillStyle = '#ffffff'; g.fillRect(x + 11, y - 3, 2, 2); }
}
function drawHUD() {
  drawBar(8, 8, 'UMINE', P.hp, playerMaxHP(), '#7fd6ff', 'l');
  if (boss.state !== 'off') drawBar(VW - 8, 8, BOSS_TYPES[curArea.boss].hud, boss.hpShown, bossCfg().hp, '#ff5d5d', 'r');
  g.fillStyle = 'rgba(10,8,24,0.72)'; g.fillRect(6, 26, 92, 12);
  drawText('MP', 8, 28, 'c', 1);
  for (let i = 0; i < CONFIG.magicMaxMP; i++) {
    g.fillStyle = i < magic.mp ? '#72dafa' : '#29394d'; g.fillRect(26 + i * 3, 30, 2, 5);
  }
  if (equippedSupport()) {
    const sid = equippedSupport(), lbl = ({ tobiume: 'KICK', neenia: 'RAIN', seiten: 'SONG', astarte: 'SLASH', lily: 'LIVE' }[sid] || 'HELP');
    const unavailable = sid === 'lily' && (!stageUmimi.given || stageUmimi.down || stageUmimi.hp <= 0);
    drawText(unavailable ? (stageUmimi.down ? 'SUP DOWN' : 'SUP WAIT') : support.used ? 'SUP USED' : 'SUP B: ' + lbl, 8, 42, unavailable || support.used ? 'b' : 'y', 1);
    if (sid === 'lily' && stageUmimi.given) drawText('UMIMI ' + stageUmimi.hp + '/' + stageUmimi.maxHp, 8, 54, stageUmimi.down ? 'b' : 'c', 1);
  }
  if (hardMode) drawText('HARD', VW - 8, 28, 'r', 1, 'r');
  if (DEBUG.god) drawText('GOD', 8, equippedSupport() === 'lily' && stageUmimi.given ? 66 : 54, 'g', 1);
}
function drawHitboxes(camX) {
  g.strokeStyle = '#00ff00'; g.lineWidth = 1;
  g.strokeRect(Math.round(P.x - camX) + 0.5, Math.round(P.y) + 0.5, P.w - 1, P.h - 1);
  for (const e of enemies) if (e.alive && e.active) g.strokeRect(Math.round(e.x - camX) + 0.5, Math.round(e.y) + 0.5, e.w - 1, e.h - 1);
  g.strokeStyle = '#ffff00'; // hurtboxes (what shots/arrows hit)
  for (const e of enemies) if (e.alive && e.active && e.hurtUp) g.strokeRect(Math.round(e.x - camX) + 0.5, Math.round(e.y - e.hurtUp) + 0.5, e.w - 1, e.h + e.hurtUp - 1);
  g.strokeStyle = '#00ff00';
  if (stageUmimi.active && stageUmimi.given && !stageUmimi.down) { const ub = stageUmimiBox(); g.strokeRect(Math.round(ub.x - camX) + 0.5, Math.round(ub.y) + 0.5, ub.w - 1, ub.h - 1); }
  if (boss.state !== 'off') g.strokeRect(Math.round(boss.x - camX) + 0.5, Math.round(boss.y) + 0.5, boss.w - 1, boss.h - 1);
}
function dim(a) { g.fillStyle = 'rgba(8,6,20,' + a + ')'; g.fillRect(0, 0, VW, VH); }

function renderTitle() {
  drawBackground(titleScroll);
  const HM = TITLE_HARD;
  g.fillStyle = hardMode ? '#4b1423' : 'rgba(12,8,30,0.82)'; g.fillRect(HM.x, HM.y, HM.w, HM.h);
  rectLine(HM.x, HM.y, HM.w, HM.h, hardMode ? '#ff667d' : '#4a5680');
  drawText(hardMode ? 'HARD ON' : 'HARD OFF', HM.x + HM.w / 2, HM.y + 4, hardMode ? 'r' : 'b', 1, 'c');
  g.drawImage(levelCv, 0, 208, VW, 32, 0, 208, VW, 32);
  g.fillStyle = 'rgba(12,8,30,0.78)'; g.fillRect(0, 18, VW, 56);
  g.fillStyle = '#ffd84a'; g.fillRect(0, 18, VW, 1); g.fillRect(0, 73, VW, 1);
  drawText('ROCKSIDE II', VW / 2 + 2, 29, 'k', 3, 'c');
  drawText('ROCKSIDE II', VW / 2, 26, 'y', 3, 'c');
  drawText('SEQUEL BASE / MODEL TEST', VW / 2, 52, 'c', 1, 'c');
  drawText('VER ' + GAME_VERSION, VW / 2, 62, 'b', 1, 'c');
  if (isCleared('final')) { // game cleared: small star mark
    const sx = VW - 38, sy = 58; g.fillStyle = '#120e24'; g.fillRect(sx - 1, sy - 1, 34, 11); g.fillStyle = (frame >> 4) & 1 ? '#ffd84a' : '#fff4b0';
    g.fillRect(sx + 3, sy + 1, 3, 7); g.fillRect(sx + 1, sy + 3, 7, 3); g.fillRect(sx + 2, sy + 2, 5, 5); drawText('CLEAR', sx + 10, sy + 2, 'y', 1);
  }
  // hero name: 海音 UMINE
  g.drawImage(kanjiCv, 78, 82);
  drawTextShadow('UMINE', 118, 85, 'c', 2);
  if (((frame >> 4) & 3) !== 3) drawTextShadow('TAP TO START', VW / 2, 118, 'w', 2, 'c');
  drawText('OR PRESS ENTER', VW / 2, 134, 'b', 1, 'c');
  // Umine + a Trundlebot, with a water bullet flying between them
  if (SEQUEL_MODEL.size !== 32 && SEQUEL_MODEL.frames.length) drawSequelAt(6, 46, 208, 1, false, 64); else if (SHEETS.kanon) g.drawImage(SHEETS.kanon[8].r, 14, 144, 64, 64); else g.drawImage(SPR.hero.stand[1].r, 18, 148, HERO_W * 2, HERO_H * 2);
  const px = 72 + ((frame * 2) % 120);
  g.drawImage(SPR.shot.r, px, 178, 16, 12);
  g.drawImage(SPR.walker[(frame >> 3) & 1].l, 200, 164, 32, 44);
  drawText('MOVE: ARROWS/A D   JUMP: Z/SPACE', VW / 2, 218, 'w', 1, 'c');
  drawText('SHOT: X/J    SOUND: M', VW / 2, 228, 'w', 1, 'c');
  if (clearedCount() > 0) { // erase saved progress (tap twice / Delete key twice)
    const R = TITLE_RESET, armed = resetArmT > 0;
    g.fillStyle = armed ? '#6a1830' : 'rgba(12,8,30,0.8)'; g.fillRect(R.x, R.y, R.w, R.h);
    g.fillStyle = armed ? '#ff8a8a' : '#4a5680'; g.fillRect(R.x, R.y, R.w, 1); g.fillRect(R.x, R.y + R.h - 1, R.w, 1); g.fillRect(R.x, R.y, 1, R.h); g.fillRect(R.x + R.w - 1, R.y, 1, R.h);
    drawText(armed ? 'TAP AGAIN' : 'ERASE DATA', R.x + R.w / 2 + 1, R.y + 4, armed ? 'r' : 'b', 1, 'c');
  }
}
// ---------------------------------------------------------------------
//  STAGE SELECT (3x3) + boss-intro flash
// ---------------------------------------------------------------------
function areaNo(a) { return a.no || (a.slot < 4 ? a.slot + 1 : a.slot); } // AREA number (AREAS[].no)
function rectLine(x, y, w, h, col) { g.fillStyle = col; g.fillRect(x, y, w, 1); g.fillRect(x, y + h - 1, w, 1); g.fillRect(x, y, 1, h); g.fillRect(x + w - 1, y, 1, h); }
// 40x40 portrait: a 20x20 crop of a sheet frame drawn at 2x (procedural art if the sheet is not loaded)
// shadow: true -> generic DARK silhouette mode (shadowFrames); rescued friends show their normal face
// 48x48 portrait box: the 24x24 face icon at 2x (dark face until cleared/rescued, then the normal face).
// Fallback when the icons are missing: 20x20 sheet crop at 2x (centred), then procedural art.
function portraitFace(a) { return (isRescued(a.friend) || isCleared(a.id)) ? a.faceRescued : a.face; }
function drawPortrait(a, x, y) {
  const rescued = isRescued(a.friend) || isCleared(a.id), fk = portraitFace(a);
  if (fk && SHEETS[fk]) { g.drawImage(SHEETS[fk][0].r, x, y, 48, 48); return; }
  x += 4; y += 4;
  let P0 = rescued && a.portraitRescued ? a.portraitRescued : a.portrait; if (!P0) return;
  const shadow = P0.shadow && !rescued;
  const fr = shadow ? shadowFrames(P0.sheet) : SHEETS[P0.sheet];
  if (fr && fr[P0.frame]) { g.drawImage(fr[P0.frame].r, P0.x, P0.y, P0.size, P0.size, x, y, 40, 40); return; }
  // procedural fallback art (?sprites=0)
  const pal = (a.friend === 'tobiume' && !rescued) ? 'dark' : 'normal';
  if (a.friend === 'tobiume') g.drawImage(SPR.tobi[pal].idle[0].r, 10, 0, 20, 20, x, y, 40, 40);
  else { const k = { neenia: 'N', seiten: 'S', astarte: 'A', shiranui: 'K', diceroll: 'R' }[a.friend]; if (k) { g.drawImage(SPR.ally[k][0].r, 6, 2, 20, 20, x, y, 40, 40); if (shadow) { g.fillStyle = 'rgba(16,8,32,0.8)'; g.fillRect(x, y, 40, 40); } } }
}
function drawCheck(x, y) { // 13x10 green check mark with dark outline
  const pts = [[0, 5], [1, 6], [2, 7], [3, 8], [4, 7], [5, 6], [6, 5], [7, 4], [8, 3], [9, 2], [10, 1], [11, 0]];
  g.fillStyle = '#0a2010'; for (const [px, py] of pts) g.fillRect(x + px - 1, y + py - 1, 4, 4);
  g.fillStyle = '#6cf07a'; for (const [px, py] of pts) g.fillRect(x + px, y + py, 2, 2);
}
function drawPadlock(cx, cy) {
  g.fillStyle = '#7a6a3a'; g.fillRect(cx - 6, cy - 12, 12, 2); g.fillRect(cx - 7, cy - 11, 2, 9); g.fillRect(cx + 5, cy - 11, 2, 9); // shackle
  g.fillStyle = '#c8a848'; g.fillRect(cx - 9, cy - 3, 18, 14); g.fillStyle = '#f0d070'; g.fillRect(cx - 9, cy - 3, 18, 2);
  g.fillStyle = '#3a2a10'; g.fillRect(cx - 1, cy + 1, 3, 3); g.fillRect(cx, cy + 3, 1, 4);
}
// English cell label: long area names use their short form so they fit the 76px cell.
function cellLabel(a) { return textWidth(a.en, 1) <= SEL.cw - 4 ? a.en : (a.enShort || a.en.slice(0, Math.floor((SEL.cw - 3) / 6))); }
function drawCell(slot) {
  const R = cellRect(slot), a = areaAtSlot(slot);
  const locked = !!(a && a.final && !finalUnlocked()), playable = !!(a && a.map) && !locked, cleared = !!(a && isCleared(a.id));
  const friendCell = !!(a && (a.face || a.portrait)) && !locked;     // a DARK <friend> boss slot (playable or coming soon)
  g.fillStyle = playable ? '#1c2244' : friendCell ? '#1a1630' : '#141830'; g.fillRect(R.x, R.y, R.w, R.h);
  rectLine(R.x, R.y, R.w, R.h, cleared ? '#4a9a6a' : playable ? '#4a5a90' : friendCell ? '#44305e' : '#2c3558');
  const px = R.x + 12, py = R.y + 2;                      // 52x52 portrait frame (48x48 inside = face icon at 2x)
  g.fillStyle = '#080a16'; g.fillRect(px, py, 52, 52);
  rectLine(px, py, 52, 52, cleared ? '#8af0a0' : playable ? '#9aa8e0' : friendCell ? '#7a4a9a' : a && a.final ? '#7a6a3a' : '#3a4468');
  if (friendCell) {
    if (playable) { const th = THEMES[a.theme] || THEMES.sunset; // portrait background = the area's sky colours
      g.fillStyle = th.sky[cleared ? 2 : 1]; g.fillRect(px + 2, py + 2, 48, 48); g.fillStyle = th.sky[cleared ? 1 : 2]; g.fillRect(px + 2, py + 36, 48, 14); }
    else { g.fillStyle = '#5a3c80'; g.fillRect(px + 2, py + 2, 48, 48); g.fillStyle = '#7a4c90'; g.fillRect(px + 2, py + 34, 48, 16); }
    drawPortrait(a, px + 2, py + 2);
    if (a.final && !cleared) { g.fillStyle = 'rgba(14,8,30,' + (0.72 + Math.sin(frame * 0.08) * 0.08) + ')'; g.fillRect(px + 2, py + 2, 48, 48); drawTextShadow('?', px + 27, py + 16, 'c', 3, 'c'); }
    if (cleared) { // normal face stays visible: CLEAR ribbon along the bottom + check badge
      g.fillStyle = 'rgba(6,20,12,0.82)'; g.fillRect(px + 2, py + 40, 48, 10); drawText('CLEAR', px + 26, py + 42, 'g', 1, 'c');
      g.fillStyle = '#0a2010'; g.fillRect(px + 35, py + 3, 15, 13); drawCheck(px + 37, py + 5);
    }
  } else if (a && a.final) {
    if (locked) drawPadlock(px + 26, py + 26);
    else { const s = SPR.star; g.drawImage(s.r, px + 10, py + 10, 32, 32); if ((frame >> 3) & 1) { g.fillStyle = 'rgba(255,255,255,0.25)'; g.fillRect(px + 2, py + 2, 48, 48); } }
  } else { // ??? reserved slot for a future friend
    drawTextShadow('?', px + 27, py + 14, 'b', 4, 'c');
  }
  const en = playable ? cellLabel(a) : a && a.final ? 'LOCKED' : a && a.reserved ? 'LOCKED' : 'COMING SOON';
  drawText(en, R.x + R.w / 2, R.y + R.h - 7, playable ? (cleared ? 'g' : 'w') : 'b', 1, 'c');
}
function renderSelect() {
  g.fillStyle = '#0b0e20'; g.fillRect(0, 0, VW, VH);
  for (let i = 0; i < 48; i++) { // drifting stars
    const h = hash(i, 11), sp = ((h >>> 20) & 3) + 1; let x = Math.floor((h % VW) - titleScroll * sp * 0.5) % VW; if (x < 0) x += VW;
    g.fillStyle = (h >> 8) & 1 ? '#3a4270' : '#262c50'; g.fillRect(x, (h >>> 9) % VH, 1, 1);
  }
  g.fillStyle = 'rgba(22,26,56,0.96)'; g.fillRect(0, 0, VW, 21); g.fillStyle = '#ffd84a'; g.fillRect(0, 21, VW, 1);
  drawTextShadow('STAGES', 170, 6, 'y', 2, 'c');
  const B = SEL_BACK; g.fillStyle = '#141a30'; g.fillRect(B.x, B.y, B.w, B.h); rectLine(B.x, B.y, B.w, B.h, '#4a5680'); drawText('TITLE', B.x + B.w / 2 + 1, B.y + 4, 'b', 1, 'c');
  const SB = SEL_SUPPORT; g.fillStyle = progress.support && supportUnlocked(progress.support) ? '#53304b' : '#202039';
  g.fillRect(SB.x, SB.y, SB.w, SB.h); rectLine(SB.x, SB.y, SB.w, SB.h, '#d087ac');
  drawText(progress.support && supportUnlocked(progress.support) ? 'SUP:' + SUPPORT_TAGS[progress.support] : 'SUP: ---', SB.x + SB.w / 2, SB.y + 5, 'w', 1, 'c');
  drawText(clearedCount() + '/8', VW - 5, 9, clearedCount() ? 'g' : 'b', 1, 'r');
  for (let slot = 0; slot < 9; slot++) drawCell(slot);
  const R = cellRect(selCursor);
  if (state === 'areaIntro') { // chosen: the cell flashes quickly
    if ((stateT >> 2) & 1) { g.fillStyle = 'rgba(255,255,255,0.75)'; g.fillRect(R.x, R.y, R.w, R.h); }
    rectLine(R.x - 2, R.y - 2, R.w + 4, R.h + 4, '#ffffff'); rectLine(R.x - 1, R.y - 1, R.w + 2, R.h + 2, '#ffffff');
  } else if (((frame >> 3) & 3) !== 3) { // classic blinking cursor with corner brackets
    const c = (frame >> 2) & 1 ? '#ffd84a' : '#fff4b0';
    rectLine(R.x - 2, R.y - 2, R.w + 4, R.h + 4, c); rectLine(R.x - 1, R.y - 1, R.w + 2, R.h + 2, c);
    g.fillStyle = '#ffffff';
    for (const [cx, cy, dx, dy] of [[R.x - 3, R.y - 3, 1, 1], [R.x + R.w + 2, R.y - 3, -1, 1], [R.x - 3, R.y + R.h + 2, 1, -1], [R.x + R.w + 2, R.y + R.h + 2, -1, -1]]) {
      g.fillRect(dx > 0 ? cx : cx - 7, cy, 8, 1); g.fillRect(cx, dy > 0 ? cy : cy - 7, 1, 8);
    }
  }
  blit();
  // hi-res Japanese cell names
  for (let slot = 0; slot < 9; slot++) {
    const Rc = cellRect(slot), a = areaAtSlot(slot), playable = !!(a && a.map);
    const jp = playable ? a.name : a && a.final ? a.name : a && a.bossName ? a.bossName : '???';
    const col = playable ? (isCleared(a.id) ? '#b0ffc0' : '#ffffff') : a && a.final ? '#e8d090' : a && a.bossName ? '#d0a0ff' : '#8a96c0';
    drawHiText(jp, Rc.x + Rc.w / 2, Rc.y + 54.5, 7.5, col, '#080a16');
  }
  if (selMsg) drawSelMessage(selMsg, Math.min(1, (110 - selMsgT) / 6 + 0.2));
}
function drawSelMessage(m, alpha) { // centred message box over the grid (hi-res)
  const s = hiS(), x = Math.round(14 * s), w = Math.round(228 * s), y = Math.round(92 * s), h = Math.round(54 * s);
  sctx.save(); sctx.globalAlpha = alpha;
  sctx.fillStyle = '#0a0a1c'; sctx.strokeStyle = '#ffd84a'; sctx.lineWidth = Math.max(2, Math.round(s));
  roundRect(x, y, w, h, Math.round(3 * s)); sctx.fill(); sctx.stroke(); sctx.restore();
  drawHiText(m.jp, VW / 2, 103, 8.5, '#ffffff', null);
  drawHiText(m.en, VW / 2, 124, 8, '#ffd84a', null);
}
function renderAreaIntro() {
  const t = stateT - 24, a = introArea;
  g.fillStyle = '#05060f'; g.fillRect(0, 0, VW, VH);
  for (let i = 0; i < 56; i++) { // stars streaking left
    const h = hash(i, 23), sp = ((h >>> 20) & 3) + 1; let x = Math.floor((h % VW) - t * sp * 1.5) % VW; if (x < 0) x += VW;
    g.fillStyle = sp > 2 ? '#8a90c0' : '#3a4070'; g.fillRect(x, (h >>> 9) % VH, sp > 2 ? 3 : 1, 1);
  }
  const bandY = 66, bandH = 110;
  g.fillStyle = '#1c1240'; g.fillRect(0, bandY, VW, bandH);
  g.fillStyle = '#261a52'; for (let y = bandY + ((t >> 1) & 3); y < bandY + bandH; y += 4) g.fillRect(0, y, VW, 1);
  const BT = BOSS_TYPES[a.boss] || BOSS_TYPES.tobiume;
  g.fillStyle = BT.speakerColor; g.fillRect(0, bandY, VW, 2); g.fillRect(0, bandY + bandH - 2, VW, 2);
  // boss drops into the band (2x): idle frames of her DARK sheet (procedural fallback)
  const fr = SHEETS[BT.dark], size = fr ? 48 : 40;
  let img;
  if (fr) img = fr[(frame >> 4) & 1].r;
  else if (a.boss === 'tobiume') img = SPR.tobi.dark.idle[(frame >> 3) & 1].r;
  else { const k = BT.ally || 'A'; SPR.allyDark = SPR.allyDark || {}; if (!SPR.allyDark[k + 0]) SPR.allyDark[k + 0] = sheetSprite(tintCanvas(SPR.ally[k][0].r, '#1a0828', 0.72)); img = SPR.allyDark[k + 0].r; }
  const ty = bandY + bandH - 2 - size * 2 + 6, y = t < 26 ? Math.round(-size * 2 + (ty + size * 2) * (1 - Math.pow(1 - t / 26, 2))) : ty;
  g.save(); g.beginPath(); g.rect(0, 0, VW, bandY + bandH - 2); g.clip();
  g.drawImage(img, 14, y, size * 2, size * 2); g.restore();
  // boss name typed letter by letter (pixel font), JP name below (hi-res, after blit)
  const words = a.bossEn.split(' '); let n = Math.max(0, Math.floor((t - 30) / 3));
  for (let i = 0; i < words.length; i++) {
    const wd = words[i].slice(0, Math.max(0, n)); n -= words[i].length;
    drawTextShadow(wd, 128, bandY + 18 + i * 16, 'y', 2);
  }
  drawText('AREA ' + areaNo(a), VW / 2, 24, 'c', 1, 'c');
  drawText(a.en, VW / 2, 50, 'w', 1, 'c');
  if (t > 70 && ((frame >> 4) & 1)) drawTextShadow('TAP TO START', VW / 2, 206, 'w', 1, 'c');
  if (t < 8) { g.fillStyle = 'rgba(255,255,255,' + (1 - t / 8) + ')'; g.fillRect(0, 0, VW, VH); } // white flash
  blit();
  drawHiText(a.name, VW / 2, 33, 10, '#ffd6ec', '#120e24');
  if (t > 30 + a.bossEn.replace(' ', '').length * 3) drawHiText(a.bossName, 188, bandY + 58, 12, '#ffffff', '#3a0a28');
  if (t > 50 && a.bossAlias) drawHiText('〜 ' + a.bossAlias + ' 〜', 188, bandY + 80, 7.5, BT.speakerColor, '#120e24');
}

function render() {
  g.setTransform(1, 0, 0, 1, 0, 0);
  if (state === 'title') { renderTitle(); blit(); drawHiText('〜 水の魔女と堕ちた天使 〜', VW / 2, 102, 8, '#ffd6ec', '#120e24'); return; }
  if (state === 'select' || (state === 'areaIntro' && stateT < 24)) { renderSelect(); return; }
  if (state === 'areaIntro') { renderAreaIntro(); return; }
  if (state === 'theEnd') { renderTheEnd(); return; }
  if (state === 'ending' && typeof renderEnding === 'function') { renderEnding(); return; }
  const camX = Math.round(cam.x);
  drawBackground(camX);
  let sx = 0, sy = 0;
  if (shakeT > 0) { sx = (shakeT & 1 ? 1 : -1) * shakeMag; sy = ((shakeT >> 1) & 1 ? 1 : -1) * Math.max(1, shakeMag >> 1); }
  g.setTransform(1, 0, 0, 1, sx, sy);
  g.drawImage(levelCv, camX, 0, VW, VH, 0, 0, VW, VH);
  drawDoor(camX); drawAllies(camX); drawStageUmimi(camX);
  for (let i = 0; i < enemies.length; i++) { const e = enemies[i]; if (e.alive && e.active) drawEnemy(e, camX); }
  drawLilyBossSpotlight(camX);
  if (curArea.boss === 'lily' && bossUmimi.active && bossUmimi.state === 'platform') drawBossUmimi(camX);
  drawBoss(camX);
  if (!(curArea.boss === 'lily' && bossUmimi.active && bossUmimi.state === 'platform')) drawBossUmimi(camX);
  drawWaterOrb(camX);
  drawSupport(camX);
  if (!(state === 'ready' && (stateT & 8))) drawPlayer(camX);
  for (let i = 0; i < shots.length; i++) if (shots[i].active) drawShot(shots[i], camX);
  drawArrows(camX);
  for (let i = 0; i < bullets.length; i++) if (bullets[i].active) drawBullet(bullets[i], camX);
  drawParticles(camX);
  if (curArea.final) drawFinalWorld(camX);
  if (DEBUG.hitbox) drawHitboxes(camX);
  g.setTransform(1, 0, 0, 1, 0, 0);
  if (!(curArea.final && (state === 'climax' || state === 'finale'))) drawHUD();
  if (state === 'ready' && ((stateT >> 3) & 1) === 0) drawTextShadow('GET SET!', VW / 2, 104, 'y', 2, 'c');
  if (state === 'bossIntro' && introPhase === 2 && (frame >> 3) & 1) drawTextShadow('WARNING', VW / 2, 60, 'r', 2, 'c');
  if (state === 'gameover') {
    dim(Math.min(0.7, stateT / 30));
    drawTextShadow('GAME OVER', VW / 2, 84, 'r', 3, 'c');
    if (stateT > 30 && (frame >> 5) & 1) drawTextShadow('TAP OR ENTER TO RETRY', VW / 2, 120, 'w', 1, 'c');
    drawText(checkpoint ? 'RESTART FROM CHECKPOINT' : 'RESTART FROM STAGE START', VW / 2, 136, 'b', 1, 'c');
  }
  if (state === 'clear') {
    dim(Math.min(0.6, stateT / 40));
    drawTextShadow('STAGE CLEAR!', VW / 2, 70, 'y', 3, 'c');
    drawText(BOSS_TYPES[curArea.boss].clearEn, VW / 2, 100, 'c', 1, 'c');
    const secs = Math.floor(stats.playFrames / 60);
    drawText('TIME ' + Math.floor(secs / 60) + ':' + (secs % 60 < 10 ? '0' : '') + (secs % 60) + '   KILLS ' + stats.kills, VW / 2, 114, 'w', 1, 'c');
    if (stateT > 60 && (frame >> 5) & 1) drawTextShadow('TAP OR ENTER: STAGE SELECT', VW / 2, 150, 'w', 1, 'c');
  }
  if (curArea.final) drawFinalOverlay();
  blit();
  if (support.active && support.t < 106) {
    if (support.kind === 'neenia') drawHiText('ネーニア・星降る矢雨！', VW / 2, 67, 8, '#e2ecff', '#253568');
    else if (support.kind === 'seiten') drawHiText('青天・守護の歌！', VW / 2, 67, 8, '#ffe5eb', '#661b37');
    else if (support.kind === 'astarte') drawHiText('アスターテ・月影の一閃！', VW / 2, 67, 8, '#ece7ff', '#30236e');
    else if (support.kind === 'lily') drawHiText('リリィ＆ウミミ・スターライトレイン！', VW / 2, 67, 8, '#fff1cf', '#6e285e');
    else if (support.kind === 'diceroll') { if (support.t < 90) drawHiText('ダイスロール・運命のダイス！', VW / 2, 67, 8, '#fff4d8', '#6a1020'); }
    else if (support.kind === 'shiranui') { if (support.t < 80) drawHiText('シラヌイ・狐火の舞じゃ！', VW / 2, 67, 8, '#ffe8d8', '#6e1a24'); }
    else if (support.kind === 'star') { if (support.t < 80) drawHiText('スターさん・錬金モーフスラッシュ！', VW / 2, 67, 8, '#e0f8ff', '#1d3e6e'); }
    else if (support.t < 75) drawHiText('スーパーウルトラ飛梅ちゃんキック！', VW / 2, 67, 8, '#ffe0ee', '#581d4b');
  }
  // ---- high-res overlays: speech bubbles / dialogue / Japanese lines ----
  if (state === 'play' || state === 'ready' || state === 'bossIntro') {
    for (let i = 0; i < allies.length; i++) {
      const a = allies[i]; if (a.bubbleT <= 0) continue;
      const sx2 = a.x - camX; if (sx2 < -10 || sx2 > VW + 10) continue;
      const info = a.type === 'I' ? { name: 'リリィ', color: '#d06aa8' } : ALLY_INFO[a.type];
      drawBubble(sx2, a.y - 34, info.name, info.color, a.line, a.bubbleT < 20 ? a.bubbleT / 20 : 1);
    }
  }
  const BT = BOSS_TYPES[curArea.boss];
  if (boss.state === 'rescue' && boss.t >= 100 && state === 'play') drawDialogue(BT.speaker, BT.speakerColor, BT.line, Math.min(1, (boss.t - 100) / 15), 36, BT.face); // top: keeps both characters visible
  if (state === 'clear') drawHiText(BT.clearJp, VW / 2, 126, 8, '#ffc0dc', '#120e24');
  if (curArea.final) drawFinalHi();
}
// Fill the screen at any size without shimmer: blow the frame up by a whole number with
// hard edges first, then shrink that smoothly to the real size. Every game pixel ends up
// the same width; only its outer edge is softened by under one screen pixel.
let blitMid = null, blitK = 0;
function blit() {
  const sw = screen.width, sh = screen.height;
  const k = Math.max(1, Math.ceil(Math.min(sw / VW, sh / VH) - 1e-6));
  if (VW * k === sw && VH * k === sh) { sctx.imageSmoothingEnabled = false; sctx.drawImage(buf, 0, 0, sw, sh); return; }
  if (!blitMid || blitK !== k) { blitMid = mkCanvas(VW * k, VH * k); blitK = k; }
  const mg = blitMid.getContext('2d');
  mg.imageSmoothingEnabled = false; mg.drawImage(buf, 0, 0, VW * k, VH * k);
  sctx.imageSmoothingEnabled = true; sctx.imageSmoothingQuality = 'high';
  sctx.drawImage(blitMid, 0, 0, sw, sh);
  sctx.imageSmoothingEnabled = false;
}

// =====================================================================
//  Main loop: fixed 60Hz simulation, render every animation frame
// =====================================================================
const STEP = 1000 / 60;
let lastT = performance.now(), acc = 0;
function loop(now) {
  requestAnimationFrame(loop);
  let dt = now - lastT; lastT = now;
  if (dt > 250) dt = 250; if (dt < 0) dt = 0;
  acc += dt; let n = 0;
  while (acc >= STEP && n < 5) { update(); acc -= STEP; n++; }
  if (n >= 5) acc = 0;
  render();
}
loadSheets();
resetStage(false); setState('title');
if (DEBUG.area) { const a = AREAS.find(x => x.no === DEBUG.area && x.map); if (a) startGame(a); } // ?area=N: straight into the stage
if (DEBUG.ending) startEnding(); // ?ending=1: straight to the ending party + credits
requestAnimationFrame(loop);

// Debug / test hook (harmless in production)
window.ROCKSIDE = { CONFIG, P, boss, enemies, stats, cam, layout, DEBUG, shots, bullets, allies, arrows, SHEETS_LOADED, SHEET_DEFS,
  AREAS, progress, support, stageUmimi, magic, PROGRESS_KEY, SEQUEL_MODEL, setSequelModel, sequelMuzzle, SEL, SEL_BACK, SEL_SUPPORT, TITLE_HARD, TITLE_RESET, cellRect, clearedCount, finalUnlocked,
  get hardMode() { return hardMode; }, get playerMaxHP() { return playerMaxHP(); },
  get state() { return state; }, get stateT() { return stateT; }, get checkpoint() { return checkpoint; },
  get selCursor() { return selCursor; }, get selMsg() { return selMsg; }, get curArea() { return curArea.id; }, get bossSeen() { return boss.seen.slice(); }, get floorY() { return FLOOR_Y; }, get resetArmed() { return resetArmT > 0; },
  teleport(x, y) { P.x = x; P.y = y; P.vx = 0; P.vy = 0; cam.x = clampCam(x - VW / 2); },
  _test: { loadArea, isCleared, isRescued, keys, inp, portraitFace, solidAt: solid, barGeom, cellLabel }, BOSS_TYPES,
  get ending() { return { phase: ENDING.phase, t: ENDING.t, credY: ENDING.credY, thanksT: ENDING.thanksT, h: creditsHeight() }; },
  get final() { return { phase: FINAL.phase, rushIdx: FINAL.rushIdx, climaxT: FINAL.climaxT, finaleI: FINAL.finaleI, swallowed: FINAL.swallowed, boss: curArea.boss }; },
  get roomX() { return ROOM_X; }, get cpX() { return CP_C * TS; }, get levelW() { return LEVEL_W; } };
if (document.modelContext?.registerTool) {
  const lifetime = new AbortController();
  const tools = [
    {name:'read_sequel_model',description:'Read the selected Umine model and sequel test state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({size:SEQUEL_MODEL.size,loaded:SEQUEL_MODEL.frames.length===8,state,health:P.hp})},
    {name:'set_sequel_model',description:'Select the same model size as the visible comparison buttons.',inputSchema:{type:'object',properties:{size:{type:'integer',enum:[32,40,48]}},required:['size'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||Object.keys(input).length!==1||!Number.isInteger(input.size))throw new Error('Expected a model size');setSequelModel(input.size);return {size:SEQUEL_MODEL.size,loaded:SEQUEL_MODEL.frames.length===8};}}
  ];
  for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}}
  window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});
}
</script>
</body>
</html>
